// Extracted from https://pandoc.org/MANUAL.html#pandocs-markdown for platforms
// where the runtime man page is unavailable.
const FALLBACK_EXTENSION_DESCRIPTION_LINES = [
    'abbreviations\tParses PHP Markdown Extra abbreviation keys, like *[HTML]: Hypertext Markup Language',
    'alerts\tSupports GitHub-style Markdown alerts, like > [!TIP] > Helpful advice for doing things better or more easily.',
    'all_symbols_escapable\tExcept inside a code block or inline code, any punctuation or space character preceded by a backslash will be treated literally, even if it would normally indicate formatting. Thus, for example, if one writes *\\*hello\\**',
    'amuse\tIn the muse input format, this enables Text::Amuse extensions to Emacs Muse markup.',
    'angle_brackets_escapable\tAllow < and > to be backslash-escaped, as they can be in GitHub flavored Markdown but not original Markdown. This is implied by pandoc\'s default all_symbols_escapable.',
    'ascii_identifiers\tCauses the identifiers produced by auto_identifiers to be pure ASCII. Accents are stripped off of accented Latin letters, and non-Latin letters are omitted.',
    'attributes\tAllows attributes to be attached to any inline or block-level element when parsing commonmark. The syntax for the attributes is the same as that used in header_attributes.',
    'auto_identifiers\tA heading without an explicitly specified identifier will be automatically assigned a unique identifier based on the heading text.',
    'autolink_bare_uris\tMakes all absolute URIs into links, even when not surrounded by pointy braces <...>.',
    'backtick_code_blocks\tSame as fenced_code_blocks, but uses backticks (`) instead of tildes (~).',
    'blank_before_blockquote\tOriginal Markdown syntax does not require a blank line before a block quote. Pandoc does require this except at the beginning of the document.',
    'blank_before_header\tOriginal Markdown syntax does not require a blank line before a heading. Pandoc does require this except at the beginning of the document.',
    'bracketed_spans\tA bracketed sequence of inlines, as one would use to begin a link, will be treated as a Span with attributes if it is followed immediately by attributes: [This is *some text*]{.class key="val"}',
    'citations\tTo cite a bibliographic item with an identifier foo, use the syntax @foo. Normal citations should be included in square brackets, with semicolons separating distinct items.',
    'definition_lists\tPandoc supports definition lists, using the syntax of PHP Markdown Extra with some extensions.',
    'east_asian_line_breaks\tCauses newlines within a paragraph to be ignored, rather than being treated as spaces or hard line breaks, when they occur between two East Asian wide characters.',
    'element_citations\tIn the jats output formats, this causes reference items to be replaced with <element-citation> elements.',
    'emoji\tParses textual emojis like :smile: as Unicode emoticons.',
    'empty_paragraphs\tAllows empty paragraphs. By default empty paragraphs are omitted.',
    'escaped_line_breaks\tA backslash followed by a newline is also a hard line break.',
    'example_lists\tThe special list marker @ can be used for sequentially numbered examples throughout the document.',
    'fancy_lists\tAllows ordered list items marked with uppercase and lowercase letters and roman numerals, in addition to Arabic numerals.',
    'fenced_code_attributes\tAllows attributes to be attached to fenced or backtick code blocks.',
    'fenced_code_blocks\tSupports fenced code blocks delimited by rows of three or more tildes.',
    'fenced_divs\tAllows special fenced syntax for native Div blocks with attributes.',
    'footnotes\tAllows footnotes using Pandoc Markdown footnote references and definitions.',
    'four_space_rule\tSelects the pandoc <= 2.0 behavior for parsing lists, so that four spaces indent are needed for list item continuation paragraphs.',
    'gfm_auto_identifiers\tChanges the auto_identifiers algorithm to conform to GitHub\'s method.',
    'grid_tables\tSupports grid table syntax.',
    'gutenberg\tUses Project Gutenberg conventions for plain output.',
    'hard_line_breaks\tCauses all newlines within a paragraph to be interpreted as hard line breaks instead of spaces.',
    'header_attributes\tAllows headings to be assigned attributes at the end of the heading line.',
    'ignore_line_breaks\tCauses newlines within a paragraph to be ignored rather than treated as spaces or hard line breaks.',
    'implicit_figures\tAn image with nonempty alt text, occurring by itself in a paragraph, will be rendered as a figure with a caption.',
    'implicit_header_references\tBehaves as if reference links have been defined for each heading.',
    'inline_code_attributes\tAllows attributes to be attached to verbatim text, just as with fenced code blocks.',
    'inline_notes\tAllows inline footnotes, though unlike regular notes they cannot contain multiple paragraphs.',
    'intraword_underscores\tPrevents underscores surrounded by alphanumeric characters from being interpreted as emphasis markers.',
    'latex_macros\tParses LaTeX macro definitions and applies the resulting macros to LaTeX math and raw LaTeX.',
    'line_blocks\tSupports line blocks, preserving the division into lines and leading spaces.',
    'link_attributes\tAllows attributes to be set on links and images.',
    'lists_without_preceding_blankline\tAllows a list to occur right after a paragraph, with no intervening blank space.',
    'literate_haskell\tTreats the document as literate Haskell source.',
    'mark\tHighlights text delimited with == markers.',
    'markdown_attribute\tParses Markdown inside block-level HTML tags only when the tags have markdown=1.',
    'markdown_in_html_blocks\tAllows Markdown parsing inside HTML block tags.',
    'mmd_header_identifiers\tParses MultiMarkdown-style heading identifiers in square brackets.',
    'mmd_link_attributes\tParses MultiMarkdown-style key-value attributes on link and image references.',
    'mmd_title_block\tEnables a MultiMarkdown-style title block at the top of the document.',
    'multiline_tables\tSupports tables whose header and rows can span multiple lines of text.',
    'native_divs\tUses native pandoc Div blocks for content inside <div> tags.',
    'native_numbering\tEnables native numbering of figures and tables.',
    'native_spans\tUses native pandoc Span blocks for content inside <span> tags.',
    'ntb\tIn context output, uses Natural Tables instead of the default Extreme Tables.',
    'old_dashes\tSelects the pandoc <= 1.8.2.1 behavior for parsing smart dashes.',
    'pandoc_title_block\tParses an initial pandoc title block as bibliographic information.',
    'pipe_tables\tSupports pipe table syntax.',
    'raw_attribute\tParses inline spans and fenced code blocks with a special attribute as raw content for the designated format.',
    'raw_html\tAllows raw HTML or DocBook to be inserted in Markdown outside verbatim contexts.',
    'raw_markdown\tIn ipynb input, includes Markdown cells as raw Markdown blocks for lossless round-tripping.',
    'raw_tex\tAllows raw LaTeX, TeX, and ConTeXt to be included in a document.',
    'rebase_relative_paths\tRewrites relative paths for Markdown links and images based on the containing file path.',
    'short_subsuperscripts\tParses MultiMarkdown-style short subscript and superscript syntax.',
    'shortcut_reference_links\tAllows the second pair of brackets in a shortcut reference link to be omitted.',
    'simple_tables\tSupports simple table syntax.',
    'smart\tInterprets straight quotes as curly quotes, --- as em-dashes, -- as en-dashes, and ... as ellipses.',
    'smart_quotes\tInterprets straight quotes as curly quotes during org parsing.',
    'sourcepos\tIncludes source position attributes when parsing commonmark.',
    'space_in_atx_header\tRequires a space between opening # characters and ATX heading text.',
    'spaced_reference_links\tAllows whitespace between the two components of a reference link.',
    'special_strings\tInterprets --- as em-dashes, -- as en-dashes, \\- as shy hyphen, and ... as ellipses.',
    'startnum\tPreserves ordered-list marker type and starting number where possible.',
    'strikeout\tStrikes out text delimited with ~~ markers.',
    'subscript\tAllows subscripts delimited with ~ characters.',
    'superscript\tAllows superscripts delimited with ^ characters.',
    'table_attributes\tAllows attributes to be attached to tables by including them at the end of the caption.',
    'table_captions\tAllows captions to be provided with Pandoc table syntaxes.',
    'tagging\tIn context output, produces markup suitable for tagged PDFs.',
    'task_lists\tSupports GitHub-Flavored Markdown task list syntax.',
    'tex_math_dollars\tTreats text between dollar delimiters as TeX math.',
    'tex_math_double_backslash\tTreats text between double-backslash TeX delimiters as TeX math.',
    'tex_math_gfm\tSupports GitHub-specific math formats.',
    'tex_math_single_backslash\tTreats text between single-backslash TeX delimiters as TeX math.',
    'wikilinks_title_after_pipe\tSupports wikilinks where the URL appears before the pipe and the title after it.',
    'wikilinks_title_before_pipe\tSupports wikilinks where the title appears before the pipe and the URL after it.',
    'xrefs_name\tSubstitutes internal links to headings, figures, and tables with cross-references using names or captions.',
    'xrefs_number\tSubstitutes internal links to headings, figures, and tables with cross-references using numbers.',
    'yaml_metadata_block\tAllows YAML metadata blocks delimited by --- and --- or ....'
];

export const FALLBACK_EXTENSION_DESCRIPTIONS =
    FALLBACK_EXTENSION_DESCRIPTION_LINES.reduce<Record<string, string>>((descriptions, line) => {
        const separator = line.indexOf('\t');
        if (separator < 0) return descriptions;
        descriptions[line.slice(0, separator)] = line.slice(separator + 1);
        return descriptions;
    }, {});
