import {
    createSimplePreviewFormatModule
} from './helpers';

const TEXT_FORMATS = new Set([
    'ansi',
    'asciidoc',
    'asciidoc_legacy',
    'asciidoctor',
    'bbcode',
    'bbcode_fluxbb',
    'bbcode_hubzilla',
    'bbcode_phpbb',
    'bbcode_steam',
    'bbcode_xenforo',
    'beamer',
    'biblatex',
    'bibtex',
    'commonmark',
    'commonmark_x',
    'context',
    'csljson',
    'djot',
    'docbook',
    'docbook4',
    'docbook5',
    'dokuwiki',
    'fb2',
    'gfm',
    'haddock',
    'icml',
    'ipynb',
    'jats',
    'jats_archiving',
    'jats_articleauthoring',
    'jats_publishing',
    'jira',
    'json',
    'latex',
    'man',
    'markdown',
    'markdown_github',
    'markdown_mmd',
    'markdown_phpextra',
    'markdown_strict',
    'markua',
    'mediawiki',
    'ms',
    'muse',
    'native',
    'opendocument',
    'opml',
    'org',
    'plain',
    'rst',
    'rtf',
    'tei',
    'texinfo',
    'textile',
    'typst',
    'vimdoc',
    'xml',
    'xwiki',
    'zimwiki'
]);

const TEXT_EXTENSIONS = new Set([
    '.adoc',
    '.ansi',
    '.asciidoc',
    '.bbcode',
    '.txt',
    '.md',
    '.markdown',
    '.tex',
    '.typ',
    '.rst',
    '.rtf',
    '.opml',
    '.bib',
    '.mediawiki',
    '.textile',
    '.json',
    '.xml',
    '.dj',
    '.djot',
    '.dokuwiki',
    '.fb2',
    '.fodt',
    '.haddock',
    '.icml',
    '.ipynb',
    '.jira',
    '.man',
    '.ms',
    '.muse',
    '.native',
    '.org',
    '.tei',
    '.texi',
    '.vim',
    '.xwiki',
    '.zimwiki'
]);

export function createTextPreviewFormatModule() {
    return createSimplePreviewFormatModule({
        id: 'text',
        kind: 'text',
        label: 'Text preview',
        matches: request => TEXT_FORMATS.has(request.normalizedFormat) ||
            TEXT_EXTENSIONS.has(request.normalizedExtension)
    });
}
